# Modified by octal-ip to support MQTT and an external active balancer.
# Based on the excellent work of Sebastian Muszynski: https://github.com/syssi/esphome-jk-bms
substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via bluetooth"
  mac_address: C8:47:8C:E8:1F:0F
  protocol_version: JK02

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.3.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:
api:

mqtt:
  discovery: false
  will_message:
  birth_message:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: !secret mqtt_topic
  id: jk_bms
  log_topic:
    topic: !secret mqtt_topic
    level: WARN

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 2s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "balancing"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "min cell voltage"
    max_cell_voltage:
      name: "max cell voltage"
      on_value_range:
        - above: 3.4
          then:
            - switch.turn_on: balancer0
        - below: 3.35
          then:
            - switch.turn_off: balancer0
    min_voltage_cell:
      name: "min voltage cell"
    max_voltage_cell:
      name: "max voltage cell"
    delta_cell_voltage:
      name: "delta cell voltage"
    average_cell_voltage:
      name: "average cell voltage"
    cell_voltage_1:
      name: "cell voltage 1"
    cell_voltage_2:
      name: "cell voltage 2"
    cell_voltage_3:
      name: "cell voltage 3"
    cell_voltage_4:
      name: "cell voltage 4"
    cell_voltage_5:
      name: "cell voltage 5"
    cell_voltage_6:
      name: "cell voltage 6"
    cell_voltage_7:
      name: "cell voltage 7"
    cell_voltage_8:
      name: "cell voltage 8"
    cell_voltage_9:
      name: "cell voltage 9"
    cell_voltage_10:
      name: "cell voltage 10"
    cell_voltage_11:
      name: "cell voltage 11"
    cell_voltage_12:
      name: "cell voltage 12"
    cell_voltage_13:
      name: "cell voltage 13"
    cell_voltage_14:
      name: "cell voltage 14"
    cell_voltage_15:
      name: "cell voltage 15"
    cell_voltage_16:
      name: "cell voltage 16"
    cell_resistance_1:
      name: "cell resistance 1"
    cell_resistance_2:
      name: "cell resistance 2"
    cell_resistance_3:
      name: "cell resistance 3"
    cell_resistance_4:
      name: "cell resistance 4"
    cell_resistance_5:
      name: "cell resistance 5"
    cell_resistance_6:
      name: "cell resistance 6"
    cell_resistance_7:
      name: "cell resistance 7"
    cell_resistance_8:
      name: "cell resistance 8"
    cell_resistance_9:
      name: "cell resistance 9"
    cell_resistance_10:
      name: "cell resistance 10"
    cell_resistance_11:
      name: "cell resistance 11"
    cell_resistance_12:
      name: "cell resistance 12"
    cell_resistance_13:
      name: "cell resistance 13"
    cell_resistance_14:
      name: "cell resistance 14"
    cell_resistance_15:
      name: "cell resistance 15"
    cell_resistance_16:
      name: "cell resistance 16"
    charging_power:
      name: "charging power"
    discharging_power:
      name: "discharging power"
    power_tube_temperature:
      name: "power tube temperature"
    temperature_sensor_1:
      name: "temperature sensor 1"
    temperature_sensor_2:
      name: "temperature sensor 2"
    state_of_charge:
      name: "state of charge"
    capacity_remaining:
      name: "capacity remaining"
    charging_cycles:
      name: "cycles"
    errors_bitmask:
      name: "error status"
    total_voltage:
      name: "total voltage"
    total_runtime:
      name: "total runtime"
    balancing_current:
      name: "balancing current"
    current:
      name: "current"

text_sensor:
  - platform: jk_bms_ble
    operation_status:
      name: "operation status"
    total_runtime_formatted:
      name: "total runtime formatted"

switch:
  - platform: jk_bms_ble
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

  - platform: gpio
    pin: GPIO16
    name: "${name} external balancer"
    id: balancer0
